import Profile from "@/components/Profile";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Page Profile',
  description: 'Generated by create next app',
};

export default function ProfileKaryawan() {
    return (
        <div>
            <Profile/>
        </div>
    )
}