
import react from "react";
import { Metadata } from "next";
import AdminKaryawan from "@/components/admin/PageDataKaryawan";

export const metadata: Metadata = {
  title: 'Page Data Karyawan',
  description: 'Generated by create next app',
};

export default function Karyawan() {
  return (
    <>
      <AdminKaryawan/>
    </>
  )
}
