
import react from "react";
import { Metadata } from "next";
import AdminInsident from "@/components/admin/PageDataInsiden";

export const metadata: Metadata = {
  title: 'Page Data Insiden',
  description: 'Generated by create next app',
};

export default function Insiden() {
  return (
    <>
      <AdminInsident/>
    </>
  )
}
