
import react from "react";
import { Metadata } from "next";
import AdminAdmin from "@/components/admin/PageDataAdmin";

export const metadata: Metadata = {
  title: 'Page Data Admin',
  description: 'Generated by create next app',
};

export default function PageAdminAdmin() {
  return (
    <>
      <AdminAdmin/>
    </>
  )
}
