import react from "react";
import { Metadata } from "next";
import Image from "next/image";
import cardImage from "@/assets/card-image.jpg";
import CardDataStats from "@/components/CardDataStats";
import Chart from "@/components/Chart";

export const metadata: Metadata = {
  title: "Page Admin",
  description: "Generated by create next app",
};

export default function Admin() {
  return (
    <>
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 md:gap-6 xl:grid-cols-4 2xl:gap-7.5">
        <CardDataStats />       
      </div>

      <Chart />
    </>
  );
}
