
import react from "react";
import { Metadata } from "next";
import AdminLokasi from "@/components/admin/PageDataLokasi";

export const metadata: Metadata = {
  title: 'Page Data Lokasi',
  description: 'Generated by create next app',
};

export default function Lokasi() {
  return (
    <>
      <AdminLokasi/>
    </>
  )
}
