
import react from "react";
import { Metadata } from "next";
import AdminLikelihood from "@/components/admin/PageDataLikelihood";

export const metadata: Metadata = {
  title: 'Page Data Likelihood',
  description: 'Generated by create next app',
};

export default function Likelihood() {
  return (
    <>
      <AdminLikelihood/>
    </>
  )
}
