
import react from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: 'Page Karyawan',
  description: 'Generated by create next app',
};

export default function Karyawan() {
  return (
    <>
      <h1>Hallo</h1>
    </>
  )
}
