
import react from "react";
import { Metadata } from "next";
import AdminLokasi from "@/components/admin/PageDataLokasi";
import AdminSeverity from "@/components/admin/PageDataSeverity";

export const metadata: Metadata = {
  title: 'Page Data Severity',
  description: 'Generated by create next app',
};

export default function Lokasi() {
  return (
    <>
      <AdminSeverity/>
    </>
  )
}
