
import react from "react";
import { Metadata } from "next";
import AdminInsident from "@/components/admin/PageDataInsiden";
import AdminCategory from "@/components/admin/PageDataCategory";

export const metadata: Metadata = {
  title: 'Page Data Cateory',
  description: 'Generated by create next app',
};

export default function Category() {
  return (
    <>
      <AdminCategory/>
    </>
  )
}
